### PR TITLE
Update FillPatternViewerControlWpf.xaml.cs

### PR DESCRIPTION
**Pull request by kfpopeye**
I noticed the original didn't handle complex fill patterns properly. I've made some enhancements that have fixed this. I can upload a Revit project that has the problematic fill patterns if you like.

### CODE REVIEW

**Comment by jeremytammik** [comment]
hi @kfpopeye yes please do upload a sample Revit project for testing, plus a description of the exact steps to reproduce the problematic and the improved behaviour. thank you very much!

**Comment by kfpopeye** [comment]
Hi Jeremy,

This link will download a Revit project that shows what I'm referring to: https://app.box.com/s/km97p85f67g8da89ps2jihbey9d3k8ji

There is a macro in the project that displays the new viewer next to the  old one. You'll notice the "Wood #" patterns didn't display correctly in the old viewer.

The old viewer would sometimes draw the fill grids off the bitmap when the matrix was shift too far or sometimes wouldn't fill the bitmap because it only repeated the line draw so may times. I made the viewer "smarter" by checking the shift versus the initial offset amount and checking to see if the line still intersects the bitmap.

**Comment by jeremytammik** [comment]
thank you!

**Comment by jeremytammik** [comment]
hey, i cannot compile. i guess there are some other changes required as well, maybe to other files. can you please take a quick look? thank you! i merged your pull request, integrated your changes, edited and can no longer recompile. the current state of affairs is captured in version 2015.0.0.4. thank you!

**Pull request merged**
